# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class CyclonedxCr < Formula
  desc "Crystal tool for generating cyclonedx software bill of materials (sbom) from c"
  homepage "https://github.com/hahwul/cyclonedx-cr"
  url "https://github.com/hahwul/cyclonedx-cr/archive/refs/tags/v1.0.2.tar.gz"
  sha256 "cb17fcd26d19744a5d7da700124b0c72fd2c7648c47ca56c6334d0cd66a3c422"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
system "shards build --release --no-debug --production"
bin.install "bin/cyclonedx-cr"
  end

  test do
    system "{bin}/cyclonedx-cr", "-v"
  end
end
