# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class CyclonedxCr < Formula
  desc "Crystal tool for generating cyclonedx software bill of materials (sbom) from c"
  homepage "https://github.com/hahwul/cyclonedx-cr"
  url "https://github.com/hahwul/cyclonedx-cr/archive/refs/tags/v0.1.4.tar.gz"
  sha256 "cc8d4e3fa7e4a22dfe80bf0b1f8714fd1847616e12f81c1c7d4d884a202695d5"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
system "shards build --release --no-debug --production"
bin.install "bin/cyclonedx-cr"
  end

  test do
    system "{bin}/cyclonedx-cr", "-v"
  end
end
