# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class CyclonedxCr < Formula
  desc "Crystal tool for generating cyclonedx software bill of materials (sbom) from c"
  homepage "https://github.com/hahwul/cyclonedx-cr"
  url "https://github.com/hahwul/cyclonedx-cr/archive/refs/tags/v0.1.6.tar.gz"
  sha256 "5f7f6d293182928bece9f8eae5019933c84c493df326bad36456caea7dd5e725"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
system "shards build --release --no-debug --production"
bin.install "bin/cyclonedx-cr"
  end

  test do
    system "{bin}/cyclonedx-cr", "-v"
  end
end
